# Generated by Django 6.0.6 on 2026-07-20 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_salaryhistory'),
        ('hr_operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('review_period', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('scope', models.CharField(choices=[('ORG_WIDE', 'Organization wide'), ('BRANCH', 'Branch'), ('DEPARTMENT', 'Department')], default='ORG_WIDE', max_length=20)),
                ('scope_id', models.CharField(blank=True, max_length=100)),
                ('rating_scale', models.JSONField(blank=True, default=list)),
                ('has_360_feedback', models.BooleanField(default=False)),
                ('reminder_frequency', models.PositiveIntegerField(default=7)),
                ('employee_status', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_performance_cycles_created', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(blank=True, related_name='appraisal_cycles', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
