# Generated by Django 6.0.6 on 2026-07-28 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_operations', '0003_offboardingcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='hr_operations.offboardingcase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OffboardingExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_reason', models.CharField(blank=True, max_length=255)),
                ('feedback', models.JSONField(blank=True, default=list)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('would_recommend', models.CharField(blank=True, max_length=10)),
                ('additional_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='hr_operations.offboardingcase')),
            ],
        ),
        migrations.CreateModel(
            name='OffboardingFinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_rated_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_reimbursements', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asset_non_return_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlement', to='hr_operations.offboardingcase')),
            ],
        ),
    ]
