# Generated by Django 6.0.6 on 2026-07-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentcontract',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('ZAR', 'South African Rand')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the contract'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='notice_period',
            field=models.PositiveIntegerField(default=30, help_text='Notice period in days'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='probation_period',
            field=models.PositiveIntegerField(default=0, help_text='Probation period in months'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='renewal_date',
            field=models.DateField(blank=True, help_text='Renewal reminder date', null=True),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='signed_by_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='signed_by_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='contracts/documents/')),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_list', to='contracts.employmentcontract')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
