# Generated by Django 6.0.6 on 2026-07-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_operational_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('EXECUTIVE', 'Executive'), ('HR', 'HR'), ('DEPARTMENT_HEAD', 'Department Head'), ('MANAGER', 'Manager'), ('FINANCE', 'Finance'), ('PAYROLL_OFFICER', 'Payroll Officer'), ('EMPLOYEE', 'Employee')], max_length=50, unique=True),
        ),
    ]
