# Generated by Django 6.0.6 on 2026-07-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_payrollrun_options_alter_payslip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
