# Generated by Django 6.0.6 on 2026-07-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollrun_completed_at_payrollrun_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
