# Generated by Django 6.0.6 on 2026-07-28 08:26

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_payrollrun_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='failed_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='failure_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='processed_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed With Errors'), ('FAILED', 'Failed'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='valid_payroll_month'),
        ),
    ]
